name = "Documaniac"
license = "Apache 2.0"
licenselink = "https://github.com/annersd/documaniac-theme.hugo/blob/main/LICENSE"
description = "A Hugo theme for technical documentation sites"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = "0.1.0"

[author]
  name = "Qargh"
  homepage = "https://annersd"